/**
 * RPC Manifest -- the single source of truth for all RPC commands and events
 * supported by a given version of @discord/embedded-app-sdk.
 *
 * Generated by the extraction script; consumed by the runtime host manager.
 */

/** Top-level manifest */
export interface RpcManifest {
	/** Schema version for this manifest format */
	manifest_version: 1

	/** SDK package version this was extracted from */
	sdk_version: string

	/** ISO 8601 timestamp of extraction */
	extracted_at: string

	/** Source of extraction: 'live' (from installed SDK) or 'pinned' (checked-in) */
	source: 'live' | 'pinned'

	/** All RPC commands */
	commands: RpcCommandDefinition[]

	/** All RPC events */
	events: RpcEventDefinition[]
}

/** A single RPC command definition */
export interface RpcCommandDefinition {
	/** Command name exactly as it appears in the SDK (e.g., "AUTHENTICATE") */
	name: string

	/**
	 * JSON Schema for command args (Activity -> Host).
	 * null means no args / args schema unknown.
	 */
	args_schema: Record<string, unknown> | null

	/**
	 * JSON Schema for command response data (Host -> Activity).
	 * null means void response / response schema unknown.
	 */
	response_schema: Record<string, unknown> | null

	/**
	 * Whether this command requires authentication.
	 * Derived from SDK source annotations or heuristic (default: null = unknown).
	 */
	auth_required: boolean | null

	/**
	 * Command category for organization (informational, not enforced).
	 */
	category:
		| 'handshake'
		| 'auth'
		| 'context'
		| 'voice'
		| 'iap'
		| 'social'
		| 'ui'
		| 'platform'
		| 'subscription'
		| 'analytics'
		| 'quest'
		| 'other'
}

/** A single RPC event definition */
export interface RpcEventDefinition {
	/** Event name exactly as it appears in the SDK (e.g., "READY") */
	name: string

	/**
	 * JSON Schema for subscription args (when subscribing to this event).
	 * null means no subscribe args needed.
	 */
	subscribe_args_schema: Record<string, unknown> | null

	/**
	 * JSON Schema for the event payload (Host -> Activity).
	 * null means payload schema unknown.
	 */
	payload_schema: Record<string, unknown> | null

	/**
	 * Whether this event is subscribable via SUBSCRIBE/UNSUBSCRIBE.
	 * false for lifecycle events like READY.
	 */
	subscribable: boolean

	/**
	 * Whether the host should emit a snapshot on subscribe (stateful signals).
	 */
	snapshot_on_subscribe: boolean
}
