import fs from 'node:fs/promises'
import path from 'node:path'
import { logger } from '../../core/logger.js'
import { packageJson } from './utils.js'
import { color, composeColors, type Wrapper } from '../../core/color.js'
import type { RouteEntries, ProcessedEntry } from '../../types/routes.js'

export async function getProjectSize(directory: string): Promise<number> {
	let entries = await fs.readdir(directory, { withFileTypes: true })
	let size = 0

	// devDependencies don't count towards the project size
	if (directory.endsWith('node_modules')) {
		entries = entries.filter(
			(entry) =>
				!Object.prototype.hasOwnProperty.call(packageJson.devDependencies ?? {}, entry.name) && entry.name !== '.bin'
		)
	}

	for (const entry of entries) {
		const entryPath = path.join(directory, entry.name)

		if (entry.isDirectory()) {
			size += await getProjectSize(entryPath)
		} else if (entry.isFile() && entry.name !== '.DS_Store') {
			const stats = await fs.stat(entryPath)
			size += stats.size
		}
	}

	return size
}

/**
 * Print a build summary showing routes by namespace.
 * Uses the granular route entries format.
 */
export function printBuildSummary(routeEntries: RouteEntries, totalSize: number, startTime: number, plugin: boolean) {
	// Collect all entries grouped by namespace/route
	const routeGroups: { namespace: string; route: string; entries: ProcessedEntry[] }[] = []

	// Process route entries by namespace
	for (const [namespace, routes] of Object.entries(routeEntries)) {
		for (const [routeName, entries] of Object.entries(routes)) {
			if (entries.length > 0) {
				routeGroups.push({ namespace, route: routeName, entries })
			}
		}
	}

	// Collect all keys for formatting
	const allKeys = routeGroups.flatMap((g) => g.entries.map((e) => e.key))
	const maxLength = Math.min(Math.max(...allKeys.map((k) => k.length), 15), 30)
	const maxTypeNameLength = 16 // "Namespace/Route" header length

	const headerType = 'Type'
	const headerName = 'Name'
	const headerDescription = 'Description'

	// +4 to account for autoSymbol spacing, +1 for a space between type and name
	const headerTypeSpacing = ' '.repeat(maxTypeNameLength - headerType.length + 4)
	const headerNameSpacing = ' '.repeat(maxLength - headerName.length + 1)

	let summary = color.bold(`\n${headerType}${headerTypeSpacing}${headerName}${headerNameSpacing}${headerDescription}`)
	summary += '\n' + `─`.repeat(maxLength + maxTypeNameLength + headerDescription.length + 5)

	let autoGeneratedExists = false

	// Log all routes grouped by namespace/route
	for (const group of routeGroups) {
		const type = `${group.namespace}/${group.route}`
		const truncatedType = type.length > maxTypeNameLength ? type.slice(0, maxTypeNameLength - 1) + '…' : type

		for (const entry of group.entries) {
			const isAuto = entry.metadata?.auto === true
			const autoSymbol = isAuto ? '  Δ ' : '    '
			if (isAuto) autoGeneratedExists = true

			const typeSpacing = ' '.repeat(maxTypeNameLength - truncatedType.length + 1)
			const description = (entry.metadata?.description as string) ?? ''

			summary +=
				'\n' +
				color.bold(color.cyan(truncatedType + typeSpacing + autoSymbol)) +
				`${color.bold(entry.key.padEnd(maxLength + 1))} ${description}`
		}
	}

	// Format sizing information
	let sizeText = ''
	if (totalSize < 1024 * 1024) {
		sizeText = `${(totalSize / 1024).toFixed(2)} kB`
	} else if (totalSize < 1024 * 1024 * 1024) {
		sizeText = `${(totalSize / (1024 * 1024)).toFixed(2)} MB`
	} else {
		sizeText = `${(totalSize / (1024 * 1024 * 1024)).toFixed(2)} GB`
	}

	let sizeColor: Wrapper = color.green
	if (totalSize >= 1024 * 1024 * 1024) {
		sizeColor = composeColors(color.red, color.bgBlack, color.underline)
	} else if (totalSize >= 500 * 1024 * 1024) {
		sizeColor = color.red
	} else if (totalSize >= 100 * 1024 * 1024) {
		sizeColor = color.yellow
	}

	const buildTime = Date.now() - startTime
	let buildColor: Wrapper = color.green
	if (buildTime < 5000) {
		buildColor = color.green
	} else {
		buildColor = color.yellow
	}

	if (autoGeneratedExists) {
		summary += '\n' + color.cyan(`\n${color.bold('Δ')} = Automatically generated`)
	}

	summary += '\n' + color.bold(`\n${plugin ? 'Plugin' : 'Robo'} size: `) + sizeColor(sizeText)
	if (buildTime < 1000) {
		summary += '\n' + buildColor(`Built in ${buildTime}ms\n`)
	} else {
		summary += '\n' + buildColor(`Built in ${(buildTime / 1000).toFixed(2)}s\n`)
	}

	logger.log(summary)
}
