export { color, composeColors } from './core/color.js'
export { getConfig } from './core/config.js'
export { getManifest } from './cli/compiler/manifest.js'
export { Flashcore } from './core/flashcore.js'
export { createCommandConfig } from './core/handlers.js'
export { logger, Logger } from './core/logger.js'
export { Mode } from './core/mode.js'
export { getPluginOptions } from './core/portal.js'
export { client, portal, Robo } from './core/robo.js'
export { getState, setState, State } from './core/state.js'
export type { LogDrain } from './core/logger.js'
export type * from './types/index.js'
