import { AI, ChatMessage } from '@robojs/ai'
import { CommandOptions, createCommandConfig } from 'robo.js'
import type { ChatInputCommandInteraction, GuildMember } from 'discord.js'

/*
  AI Chat Command
  
  This command enables direct chat interactions with your AI. It accepts a single
  "message" option and returns a reply generated by the AI.
  
  You can customize the description, add more options (like tone or persona), or
  change how messages are handled.
  
  Learn more:
  - Commands guide: https://robojs.dev/discord-bots/commands
  - AI plugin docs: https://robojs.dev/plugins/ai
*/
export const config = createCommandConfig({
	description: "Let's chat together!",
	options: [
		{
			name: 'message',
			required: true
		}
	]
} as const)

/**
 * Handles a slash command chat message and returns the AI's response.
 *
 * - Uses AI.chatSync for a synchronous reply suitable for slash commands.
 * - The response may include text, embeds, components, and files.
 * - Conversation context is automatically maintained by the AI per channel.
 */
export default async (interaction: ChatInputCommandInteraction, options: CommandOptions<typeof config>) => {
	// Format the user's input as a chat message for the AI engine.
	const chatMessage: ChatMessage = {
		role: 'user',
		content: options.message
	}

	// Send the message to the AI with Discord context. showTyping: false disables
	// the typing indicator since a slash command returns an immediate reply.
	const reply = await AI.chatSync([chatMessage], {
		channel: interaction.channel,
		member: interaction.member as GuildMember,
		user: interaction.user,
		showTyping: false
	})

	return {
		components: reply.components,
		content: reply.text,
		embeds: reply.embeds,
		files: reply.files
	}
}
